### ISSUE TITLE
Codegen var bug

### ISSUE THREAD

**Issue by jmorag** [laurenarnett/TensorFlock#124]
Found a bug in codegen for global vars. We currently have a test that looks like:
```
main = res;

three : Nat;
three = 3;

res : Nat;
res = 2 ^ three;
```
It returns 8 like it should. However, if we reorder the functions like so:
```
main = res;
res : Nat;
res = 2 ^ three;

three : Nat;
three = 3;
``` 
then it returns 1. This is because when we do codegen for global variables, we initialize Nats to 0, and llvm is quite happy to accept that as a valid value for `three` and raise 2 to the 0'th power and only later reassign three, since reassignment is a thing that is allowed in llvm-land. 

I think that this stems from a larger problem of us having copied large swaths of microc before we realized that our language is about as far away from microc as possible. Anyway, to solve this particular problem, we might need to change what we call `globals` into functions with 0 arguments and constant return values so that order of initialization stops mattering.

**Comment by laurenarnett** [comment]
resolved with new codegen for functions
